### PR TITLE
Capture test dependencies without realizing the tasks

### PR DESCRIPTION
**Pull request by CristianGM**
### Context
Allure-gradle plugin is forcing Gradle to realize some tasks in the consume eagerly, that makes configuration slow.

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by baev** [comment]
summon @vlsi

**Comment by vlsi** [comment]
@baev , I'm afraid I am no longer interested in `allure-gradle` development. Based on past experience, it takes ages for code review in `allure-framework/allure-gradle` to complete, which demotivates me a lot.

I deleted my fork long ago, including the unmerged branches.

**Comment by CristianGM** [comment]
As it wasn't reviewed yet, adding the second part of it.

First part was about tasks realized to expose the artifacts
Second part is about tasks realized trying to remove allure artifacts from `assemble`

**Comment by CristianGM** [comment]
Is there anything else needed?

**Review by baev — APPROVED** [review]

**Comment by baev** [comment]
@CristianGM thanks!

**Pull request merged**
