### PR TITLE
Facelift: split plugin to several ones, implement aggregation, migrate to Kotlin

### PR DESCRIPTION
**Pull request by vlsi**
This PR reworks allure-gradle plugin implementation solving all (?) the currently open issues, and making the use more predictable and user-friendly.

Note: GitHub Actions are not configured for `allure-gradle` yet, so you could check CI results at https://github.com/vlsi/allure-gradle/actions and in Gradle Build Scan (see link at the end of the run like https://scans.gradle.com/s/ylw72oz2r5nso/tests )

Here's the updated readme: https://github.com/vlsi/allure-gradle/tree/facelift

The PR is more-or-less ready.

### Open questions
* Should other adapters (e.g. `allure-selenide`) be auto-detected by default?

### Missing bits
* need test coverage of the new syntax in Groovy DSL
* signing and publishing (publishing to Central did not exist)
* ktlint? (Kotlin linting did not exist in allure-gradle)

### Tests

There are test failures, however, it looks like they identify true bugs:
* `TestNgSpiOffTest.allureReportIsNotGenerated` collects results even when `spiOff` dependency is used: 

  UPD: https://github.com/gradle/gradle/issues/17035 cause Gradle to ignore the classifier when adding a dependency with a metadata rule.

  https://scans.gradle.com/s/l6jgwoiedmtky/tests/:allure-plugin:test/io.qameta.allure.gradle.allure.TestNgSpiOffTest/allureReportIsNotGenerated?top-execution=1

* `junit5` does not collect test results (too old JUnit version? a bug in the new allure-junit5?): 

  UPD: `allureJavaVersion=2.13.5` collects data, and `allureJavaVersion=2.13.6` fails to collect JUnit5 data.

  https://scans.gradle.com/s/l6jgwoiedmtky/tests/:allure-plugin:test/io.qameta.allure.gradle.allure.DependenciesTest/shouldCreateAllureResults%5Bsrc%2Fit%2Fjunit5%20%5B5.0%5D%5D?top-execution=1

### Notes

* researchgate/gradle-release is not compatible with composite builds: https://github.com/researchgate/gradle-release/issues/304

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

**Comment by vlsi** [comment]
Unfortunately, the naming of `collect` extension clashes with Groovy's `Object#collect` method :((( https://docs.groovy-lang.org/latest/html/groovy-jdk/java/lang/Object.html#collect(groovy.lang.Closure)

```kotlin
plugins {
    id("io.qameta.allure-collect") // <-- this probably needs renaming
    id("io.qameta.allure-report")
}

allure {
    collect { // <-- this clashes with Groovy's Object.collect(Closure)
        ...
```

Does anybody have other ideas for the name?

**Comment by vlsi** [comment]
JFrog announced they would keep read-only JCenter: https://twitter.com/steveonjava/status/1387072410868797440

I am not sure if it makes sense to support "pre 2.8.0 allure versions" though. I guess the users could just upgrade.

For now, I removed all jcenter-related tests.

**Comment by vlsi** [comment]
All the tests pass now: https://github.com/vlsi/allure-gradle/runs/2482123894, https://scans.gradle.com/s/c2fh4tzo47yeu/tests

**Review by eroshenkoam — APPROVED** [review]

**Comment by eroshenkoam** [comment]
@baev lgtm?

**Comment by smohylevskyi** [comment]
@eroshenkoam is there any information on when this change is going to be released?

**Comment by smohylevskyi** [comment]
@vlsi maybe some insight from you on when this change might be released?
Thanks!

**Comment by alexsirko** [comment]
@eroshenkoam are there any updates regarding release date of this change? We would love to use latest Gradle with Allure in our project.

**Pull request merged**
